### ISSUE TITLE
Mesh breaks when updating skeleton

### ISSUE THREAD

**Issue by cadop** [cadop/HumanGenerator#44]
We have tried changing from Creating attributes to Getting and `Set()` when the already exist on this branch https://github.com/cadop/ov_makehuman/tree/mesh-fix  but continued to have issues.  

Currently we modified the code to delete the mesh and rebuild the skeleton at the end of the process, which is working enough for demos. However, this stops someone from:
- editing their human after making it
- switching rigs
- posing character while editing 

Our latest updates on `main` are from the `mesh-fix` branch, with some modifications to only build skeleton at the end.  

We are not sure what is causing the mesh to break, but rebuilding the skeleton each time we update the mesh is problematic and takes too long for a good user experience.  The current slow processing is also on the makehuman side, so updates to USD being faster won't help us.

**Comment by cadop** [comment]
Current temporary fix is to have a button that only assigns character skeleton at the end of creation.

**Comment by Fruity-Grebbles** [comment]
Resolved with update to Omniverse Create
